/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c73e10ca2457f41f867107f22fedbd64)
declare namespace Cloudflare {
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		COURSE_INDEX: Vectorize;
		REQUIREMENTS_INDEX: Vectorize;
		EMBED_MODEL: string;
		MODEL: string;
		OPENAI_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
